<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="test" tests="5" skipped="0" failures="5" errors="0" timestamp="2024-09-16T16:55:32" hostname="c03634ebb293" time="0.003065175"><testcase name="get_user_1" classname="get_user_1" time="0.001243057"><failure message="assertion failed">thread &apos;get_user_1&apos; panicked at tests/contract_testing_logic/mod.rs:84:43:
not found: Os { code: 21, kind: IsADirectory, message: &quot;Is a directory&quot; }
</failure></testcase><testcase name="add_user" classname="add_user" time="0.001275893"><failure message="assertion failed">thread &apos;add_user&apos; panicked at tests/contract_testing_logic/mod.rs:84:43:
not found: Os { code: 21, kind: IsADirectory, message: &quot;Is a directory&quot; }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
</failure></testcase><testcase name="get_user_2" classname="get_user_2" time="0.000524972"><failure message="assertion failed">thread &apos;get_user_2&apos; panicked at tests/contract_testing_logic/mod.rs:84:43:
not found: Os { code: 21, kind: IsADirectory, message: &quot;Is a directory&quot; }
</failure></testcase><testcase name="get_user_3" classname="get_user_3" time="0.000525046"><failure message="assertion failed">thread &apos;get_user_3&apos; panicked at tests/contract_testing_logic/mod.rs:84:43:
not found: Os { code: 21, kind: IsADirectory, message: &quot;Is a directory&quot; }
</failure></testcase><testcase name="get_user_4" classname="get_user_4" time="0.000370885"><failure message="assertion failed">thread &apos;get_user_4&apos; panicked at tests/contract_testing_logic/mod.rs:84:43:
not found: Os { code: 21, kind: IsADirectory, message: &quot;Is a directory&quot; }
</failure></testcase>
</testsuite>